config/routes.rb
Civiccommons::Application.routes.draw do
  devise_for :people,
             :controllers => { :registrations => 'registrations' },
             :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'new' }

  resources :events

  resources :ratings

  resources :comments

  resources :answers

  resources :issues

  resources :conversations

  resources :questions

  match '/mockup/:template_name', :to => 'mockups#show', :as => 'mockup'

  match '/mockups_index', :to => 'mockups#index', :as => 'mockups_index'

  match '/mockups', :to => 'mockups#frameset', :as => 'mockups'


  resources :people

  root :to => "homepage#show"
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
#  include ActiveModel::Validations
  has_and_belongs_to_many :issues
  has_many :events
  # has_many :comments # if we later decide to enable comments on Conversations
  has_many :questions
  has_many :answers
  has_and_belongs_to_many :guides, :class_name => 'People', :join_table => 'conversations_guides', :association_foreign_key => :guide_id

  # Return a comma-and-space-delimited list of the Issues
  # relevant to this Conversation, e.g., "Jobs, Sports, Religion"
  def issues_text
    if (issues.count > 0)
      r = ""
      issues.each do |issue|
        r += ", "
        r += issue.description
      end
      r[2,r.length-2] # lose starting comma-space
    else
      "No issues yet"
    end
  end

  # Original plan: single Moderator per Conversation.
  # New plan: Zero or more Guides per Conversation.
  # validates :moderator, :presence => :true

  def guides_text
    if (guides.count > 0)
      guides.join(", ")
    else
      "No Guides yet"
    end
  end

  #
  # Represent the "Started At" column in a reader-friendly format.
  #
  # This is kind of a kludge. It also doesn't properly say
  # "yesterday" when you're talking about New Year's Eve.
  def start_time_text
   if (started_at == nil)
     return "Don't know"
   end
   diff = started_at.yday - Time.now.yday
   sameyear = (started_at.year == Time.now.year)
   if (diff == 0 && sameyear)
     started_at.strftime("TODAY at %I:%M %p")
   elsif (diff == -1 && sameyear)
     started_at.strftime("YESTERDAY at %I:%M %p")
   else
     started_at.strftime("%A, %B %d, %Y at %I:%M %p")
   end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # GET /conversations
  # GET /conversations.xml
  def index
    @conversations = Conversation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @conversations }
    end
  end

  # GET /conversations/1
  # GET /conversations/1.xml
  def show
    @conversation = Conversation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @conversation }
    end
  end

  # GET /conversations/new
  # GET /conversations/new.xml
  def new
    @conversation = Conversation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @conversation }
    end
  end

  # GET /conversations/1/edit
  def edit
    @conversation = Conversation.find(params[:id])
  end

  # POST /conversations
  # POST /conversations.xml
  def create
    @conversation = Conversation.new(params[:conversation])
    @conversation[:started_at] = Time.now

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to(@conversation, :notice => 'Conversation was successfully created.') }
        format.xml  { render :xml => @conversation, :status => :created, :location => @conversation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @conversation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /conversations/1
  # PUT /conversations/1.xml
  def update
    @conversation = Conversation.find(params[:id])

    respond_to do |format|
      if @conversation.update_attributes(params[:conversation])
        format.html { redirect_to(@conversation, :notice => 'Conversation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @conversation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.xml
  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy

    respond_to do |format|
      format.html { redirect_to(conversations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper

def confirm_add_issue_link(id)
#  link_to 'Actually add issue I', :url => { :controller => "foo", :action => "bar", :id => id }, :remote => true
#  link_to 'Actually add issue II', :url => { :controller => "foo", :action => "bar", :id => id }, :success => "alert('Win!');$('xyzzy').show()", :failure => "alert('Lose!');$('xyzzy').show()", :class => 'privileged', :remote => true
#   = <a href="javascript:void();" onClick="alert('hi!');">Actually add issue III</a>
end

end

app/views/conversations/_chosenissues.html.haml
%strong Issues:
%ul
  - @chosenissues.each do |x|
    %li
      - @issuenumber = x
      - @issuedetail = Issue.find(@issuenumber)
      %a(href="#{url_for(:controller => 'issues', :action => 'show', :id => @issuenumber)}" title="#{@issuedetail.description}") #{@issuedetail.description}
      %a(href="javascript:void()" title="Remove this Issue" onclick='alert("Removing issue #{@issuenumber}")')
        %img(src="/images/trash-can.png")
  - if (@chosenissues.length == 0)
    %li
      This Conversation has no issues yet.
  %li
    %a(id='addissueprompt' href='javascript:void();' class='privileged' onclick='$("#addissueprompt").hide(); $("#addissue").show();')Add an Issue
    #addissue(style="display:none")
      %select(name="newissue" id="newissue")
        =render :partial => 'issues'
      -# This is "obtrusive Javascript." Should make it unobtrusive.
      -# CONFIRM button
      = confirm_add_issue_link(1)
      -# %a(href='javascript:void();' class='privileged' onclick='chooseissue(1)') Confirm adding issue
      -# CANCEL button
      %a(href='javascript:void();' class='privileged' onclick='$("#addissue").hide();$("#addissueprompt").show();') Cancel adding issue

      = link_to_function("Confirm adding issue", 'chooseissue($("#newissue").value)', :class => "privileged")

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :started_at %><br />
    <%= f.text_field :started_at %>
  </div>
  <div class="field">
    <%= f.label :finished_at %><br />
    <%= f.text_field :finished_at %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br />
    <%= f.text_field :issue_id %>
  </div>
  <div class="field">
    <%= f.label :moderator %><br />
    <%= f.text_field :moderator %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/_issues.html.haml
- @notchosenissues = @allissues.reject {|x| @chosenissues.include?(x.id)}
- @notchosenissues.each do |x|
- @value=x.id
    %option(value=@value) #{x.description}

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.haml
- content_for :main do
  %h1 Conversations
  %hr
  %table.conversation-list
    %tr
      %th
        %strong Title
      %th
        %strong Started
      %th
        %strong Issues
      %th
        %strong Guides
      %th
        %strong Summary
      %th{:colspan => 3}
        %strong Actions
    - @conversations.each do |conversation|
      %tr
        %td #{conversation.title}
        %td #{conversation.start_time_text}
        %td #{conversation.issues_text}
        %td #{conversation.guides_text}
        %td #{conversation.summary}
        %td #{link_to 'Show', conversation}
        %td #{link_to 'Edit', edit_conversation_path(conversation)}
        %td #{link_to 'Destroy', conversation, :confirm => 'Are you sure?', :method => :delete}
  #{link_to 'Start a new conversation!', new_conversation_path}

  %br
  %li
    .article.issue.conversation-ticker
      .date
        %p
          May
          %span.day 05
      %p Started discussing a new issue:
      %p
        %a(href="#" title="Starting talking about creating new jobs in Cuyahoga County")
          Creating New Jobs in Cuyahoga County

app/views/conversations/new.html.haml
- @spotlights = []
- @allissues = Issue.all(:order => 'description')
- @chosenissues = [1,3,5]
- content_for :main do
  %h1 Create a New Conversation
  - form_for :conversation, :url => {:controller => "conversations", :action => "create" } do
    .form-group
      .form-block
        %label(for="title")
          Title:
        %input(class="textbox" name="conversation[title]")
      .form-block
        %label(for="summary")
          Summary:
        %textarea(name="conversation[summary]")
      .form-block
        %label(for="image")
          Image:
        %input(class="file" type="file" name="conversation[image]")
    .form-group
      .form-block
        %label(for="event")
          Event:
        %input(class="textbox" name="event[title]")
      .related
        .form-block
          %label(for="event-when")
            When:
          = datetime_select("post", "event[when]")
        .form-block
          %label(for="event-where")
            Where:
          %input(class="textbox" name="event[where]")
    .supplementary#chosenissues
      = render :partial => 'chosenissues'
    .form-block
      %p
        %input(type="submit" class="submit" value="Create Conversation") or <a href="#" class="cancel">cancel</a>

-content_for :sidebar do
  .aside.guides
    %strong Guides
    %ul
      %li
        %a(href="#" title="George Nemeth") George Nemeth
        %a(href="#" title="Remove this Guide")
          %img(src="/images/trash-can.png")
      %li
        %a(href="#" title="Dan Moulthroup") Dan Moulthroup
        %a(href="#" title="Remove this Guide")
          %img(src="/images/trash-can.png")
    %a(href="#" title="Add Guide" class="privileged") Add Guide
  .aside.spotlight
    %strong Spotlight
    %ul
    -@spotlights.each do |s|
      %li
        %a(href="#{ link_for_spotlight(s)}" title="#{s.name}") s.name
        %a(href="#{ link_remove_spotlight(s)}" title="Remove this Spotlight")
          %img(src="/images/trash-can.png")
    %a(href="#" title="Add Spotlight" class="privileged") Add to Spotlight

app/views/conversations/show.html.haml
- content_for :main do
  %h1 Mayoral Round-up
  %select(name="comment[type]" id="comment_type")
    %option Official
    %option Other
  %textarea(name="comment[text]" id="comment_text" rows="3")
    Leave a comment...
  %a.button.tertiary(href="#" title="Save to the Stream") Save
  %hr
  %ul.event-details
    %li
      %strong Event:
      %em Roundtable Q&A 
    %li
      %strong When:
      May 24, 2010, 7:00 PM
    %li
      %strong Where:
      %a.text.button(href="#" title="City Club of Cleveland") City Club of Cleveland
  %ul
    %li
      .article.comment
        .meta
          .comment-type Official
          %a.rating(href="#" title="Rate this comment") +0
        %img(src="/images/nemeth-avatar-small.png" alt="Official Comment from George Nemeth")
        %p
          %a(href="#" title="George Nemeth's Profile")
            %strong George Nemeth
          %span.action reported:
        %p.content Dan welcomes the audience and introduces the panelists: |
                   Frank Jackson, Jane Campbell and Michael White.         |
        %p
          %a.text.button.conversation-action(href="#" title="Leave a comment") Leave a comment
          %a(href="#" class="privileged" title="Delete this comment") Delete
    %li
      .article.issue.conversation-ticker
        .date
          %p
            May
            %span.day 05
        %p Started discussing a new issue:
        %p
          %a(href="#" title="Starting talking about creating new jobs in Cuyahoga County")
            Creating New Jobs in Cuyahoga County

-content_for :sidebar do
  .aside.guides
    %strong Guides
    %ul
      %li
        %a(href="#" title="George Nemeth") George Nemeth
        = delete_button_for(:guide_id => 1)
      %li
        %a(href="#" title="Dan Moulthroup") Dan Moulthroup
        = delete_button_for(:guide_id => 2)
    %a(href="#" title="Add Guide" class="privileged") Add Guide
  .aside.spotlight
    %strong Spotlight
    %ul
      %li
        %a(href="#" title="Frank Jackson") Frank Jackson
        = delete_button_for(:spotlight_id => 3)
      %li
        %a(href="#" title="Jane Campbell") Jane Campbell
        = delete_button_for(:spotlight_id => 4)
      %li
        %a(href="#" title="Michael White") Michael White
        = delete_button_for(:spotlight_id => 5)
    %a(href="#" title="Add Guide" class="privileged") Add to Spotlight